### ISSUE TITLE
Link via region codes and not names. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/RtD3#6]
It might make sense to link via region codes and not names as this appears to be causing some issues in practice. `covidregionaldata` should have region codes for all regional data which might make this easier for our estimates. I imagine it might also be easier for other users.

**Comment by hamishgibbs** [comment]
I believe that with the variety of region codes that exist, in the UK for example, local authorities, NHS regions, counties, GADM data, or rnaturalearth data, which all have different reference codes - it may be easiest to keep relying on matching names (and warn when some names will be missing from the output). 

At the moment, the names in the dropdown are defined by the names in the time series data, not the map data, so if there are disagreements, they will still be accessible from the dropdown but will be missing from the map. This seems like a good approach to ensure that the rt data remains accessible. 

Admin name wrangling is painful but I believe that finding geodata that aligns with different region codes may be more painful, especially because of the ease of using `rnaturalearth`. 

So I support continuing to rely on admin names at the moment, but would like to hear your perspective.

**Comment by hamishgibbs** [comment]
@seabbs are you ok to close this? and continue with names for the time being?

**Comment by seabbs** [comment]
Yes I think so. My only concern is that it was a little painful linking some countries up (i.e here: https://github.com/epiforecasts/covid/blob/master/_posts/national/colombia/colombia.Rmd). However, perhaps there is no way to resolve that....
